### ISSUE TITLE
Hardening appears to cause problems with cron

### ISSUE THREAD

**Issue by Vermyndax** [GSA/ansible-os-rhel-7#14]
During the pipeline build for GSA/security-benchmarks, I had a lot of trouble getting AMIs to build with the cloudwatch role. It was consistently failing at the cron setup task during the playbook. If I run the play prior to hardening, it will succeed. Does this hardening mess with cron in any way?

**Comment by jeremy-gillikin** [comment]
@Vermyndax The hardening does change cron a bit. The [guide ](https://docs.google.com/spreadsheets/d/1mrYIgaN1941K3HbvIAYGQhHLfpZ3T70rM4UTzzb6vOM/edit#gid=1734390060) has several settings starting with 5.1.x.

**Comment by jeremy-gillikin** [comment]
@Vermyndax Should we setup time to pair and dive into this more or can this be closed?

**Comment by Vermyndax** [comment]
Let's dive into it a little bit. I can show you what role I was using and where it was failing. If I change the order to install the role prior to the hardening, it works fine. When the cloudwatch-monitoring role tries to manipulate cron, it fails. That makes me sad.
