### ISSUE TITLE
still a long way to go

### ISSUE THREAD

**Issue by dvvolodin** [GSA/ansible-os-rhel-7#4]
As it is now, the playbook is not usable in our AWS environment at all.

From what I see in the code, it's targeted towards classic stand-alone Linux PC installations with partitioned physical volumes, ext4 file systems, grub console password, etc, and there's no provision for AWS elastic volumes and no-console environments. As it is now, we cannot even apply the script to an instance and have it in a working order afterwards. The future development should certainly account for the way Linux systems are run in the AWS environment.

Otherwise, the code is very well-structured, self-explanatory and easy to follow.

Thanks!

@kishorebabu12 @ashutoy

**Comment by jeremy-gillikin** [comment]
@kishorebabu12 @ashutoy @dvvolodin 
These roles were written specifically for for cloud assets. This was tested on EC2 instances. It works fine in our VPCs and operates normally. 

This is based off what the GSA benchmark will score against on your cloud deployments. The intrusive items for legacy PC installations have been removed prior to release. If there are unique settings that break your operations, please let us know. 

I respectfully ask that you please test again.

**Comment by kishorebabu12** [comment]
@dvvolodin Did we execute the code in our DEV envrionment to evaluate the results? Please let us know. If not, please execute the code and generate results. I will setup a follow up meeting with the security team for further analysis.

**Comment by dvvolodin** [comment]
I just checked the latest commit of the script with both the vanilla AWS RHEL AMI and our own strengthened AMI. The script didn't seem to impede the functionality of either of the instances except for one obvious thing: all non-root programs that use user group names lost this functionality as their access to /etc/group was blocked by the access modes 0600.

**Comment by jeremy-gillikin** [comment]
@dvvolodin Thank you for the feedback. We've updated that setting to 0644 which should resolve the issue.

**Comment by kishorebabu12** [comment]
@jeremy-gillikin Did you get a chance to check on the additional Ansible roles for agent installs (Nessus, ODSSEC, and AV)?

**Comment by afeld** [comment]
Good to close this issue?
