### ISSUE TITLE
Doesn't launch the nested playbooks when calling the role

### ISSUE THREAD

**Issue by Vermyndax** [GSA/ansible-os-rhel-7#5]
I'm trying to launch this role from devsecops-example-pipeline. It downloaded the role, but does not execute the default playbook correctly.

Proposed fix: move os-hardening/defaults and os-hardening/tasks directories up one level.

**Comment by jeremy-gillikin** [comment]
@Vermyndax Can we close this issue? Anything else we need to address?

**Comment by Vermyndax** [comment]
Sorry, yes, this can be closed.
