### ISSUE TITLE
Move test.yml to tests directory

### ISSUE THREAD

**Issue by briankfitzwater** [GSA/ansible-os-rhel-7#9]
IAW ansible-galaxy default scaffolding, the test.yml file should go in a tests directory along with an inventory file.

#### Default scaffolding ####

```
ansible-os-rhel-7/
├── defaults
│   └── main.yml
├── handlers
│   └── main.yml
├── meta
│   └── main.yml
├── README.md
├── tasks
│   └── main.yml
├── tests
│   ├── inventory
│   └── test.yml
└── vars
    └── main.yml
```

#### tests/inventory ####

```
localhost
```

**Comment by jeremy-gillikin** [comment]
I've removed the test.yml and updated the Readme as the playbook example.
